### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Eshpelin** [chadselph/jquery-typewriter#6]
Hi, I have been here for a few times - and the demo has always been unavailable for a while now. Maybe you would like to get it back up again so that everybody can see the nice script in action?

Link Offline: `http://norad-wopr.chadselph.com/`

Error Found: `404 Not Found - nginx/1.6.2`

**Comment by chadselph** [comment]
hmm... I think I'll just move the demo to gh-pages.
